---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: yes
  serial: 1
  roles:
     - create_cluster
  handlers:
    - name: load supervisor
      shell: | 
        /opt/redislabs/bin/supervisorctl reread
        /opt/redislabs/bin/supervisorctl update